/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.ObjectOutputStream;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author melhorenvio
 */
public class TelaAdicionar extends javax.swing.JFrame  {

    /**
     * Creates new form TelaAdicionar
     */
    Agenda nova;
    File f;
    public TelaAdicionar(Agenda nova, File f) {
        this.f = f;
        this.nova = nova;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        Nome = new javax.swing.JTextField();
        Telefone = new javax.swing.JTextField();
        Sobrenome = new javax.swing.JTextField();
        Email = new javax.swing.JTextField();
        Endereco = new javax.swing.JTextField();
        numero = new javax.swing.JTextField();
        CEP = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        jLabel8.setText("jLabel8");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(600, 400));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Nome.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        Nome.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Nome.setBorder(null);
        Nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NomeActionPerformed(evt);
            }
        });
        getContentPane().add(Nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, 260, 30));

        Telefone.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        Telefone.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Telefone.setBorder(null);
        Telefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TelefoneActionPerformed(evt);
            }
        });
        getContentPane().add(Telefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, 220, 30));

        Sobrenome.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        Sobrenome.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Sobrenome.setBorder(null);
        Sobrenome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SobrenomeActionPerformed(evt);
            }
        });
        getContentPane().add(Sobrenome, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 120, 220, 30));

        Email.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        Email.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Email.setToolTipText("");
        Email.setActionCommand("<Not Set>");
        Email.setBorder(null);
        Email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmailActionPerformed(evt);
            }
        });
        getContentPane().add(Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, 260, 30));

        Endereco.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        Endereco.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Endereco.setBorder(null);
        Endereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnderecoActionPerformed(evt);
            }
        });
        getContentPane().add(Endereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 280, 270, 30));

        numero.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        numero.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        numero.setBorder(null);
        numero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numeroActionPerformed(evt);
            }
        });
        getContentPane().add(numero, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 320, 270, 30));

        CEP.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        CEP.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        CEP.setBorder(null);
        CEP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CEPActionPerformed(evt);
            }
        });
        getContentPane().add(CEP, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 240, 270, 30));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/Button.png"))); // NOI18N
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 250, 50, 50));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/Button.png"))); // NOI18N
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 30, 30));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/NOVO_CONTATO.png"))); // NOI18N
        jLabel9.setText("jLabel9");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NomeActionPerformed

    private void TelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TelefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TelefoneActionPerformed

    private void SobrenomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SobrenomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SobrenomeActionPerformed

    private void EmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmailActionPerformed

    private void EnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnderecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EnderecoActionPerformed

    private void numeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numeroActionPerformed

    private void CEPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CEPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CEPActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        ListaAgenda tela = new ListaAgenda(nova, f);
        tela.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(Nome.getText().equals("") || (Telefone.getText().equals("") && Email.getText().equals(""))){
            JOptionPane.showMessageDialog(null,  "Preencha pelo menos o nome e o telefone ou e-mail!", "Contato inválido!", JOptionPane.ERROR_MESSAGE);
        }
        else{
            Contato aux = new Contato(Nome.getText(), Sobrenome.getText(), Telefone.getText(), Email.getText(), Endereco.getText(), numero.getText(),  CEP.getText());
            aux.setNome(Nome.getText());
            aux.setSobrenome(Sobrenome.getText());
            nova.insere(aux);
            nova.ordenaLista();
            FileWriter fw;
                StringBuilder sb = new StringBuilder("");
                    for(int i = 0; i < nova.getNumeroDeContatos(); i++){
                        sb.append(nova.getListaDeContatos().get(i).getNome()+"\n"+ nova.getListaDeContatos().get(i).getSobrenome()+"\n"+nova.getListaDeContatos().get(i).getTelefone()+"\n"+nova.getListaDeContatos().get(i).getEmail()+"\n"+nova.getListaDeContatos().get(i).getRua()+"\n"+nova.getListaDeContatos().get(i).getNumero()+"\n"+nova.getListaDeContatos().get(i).getCep()+"\n");
                    }
            try {
                fw = new FileWriter(f.getName());
                fw.write(sb.toString());
                fw.close();
            } catch (IOException ex) {
                Logger.getLogger(TelaAdicionar.class.getName()).log(Level.SEVERE, null, ex);
            }
            ListaAgenda tela = new ListaAgenda(nova,f);
            tela.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAdicionar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAdicionar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAdicionar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAdicionar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new TelaAdicionar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CEP;
    private javax.swing.JTextField Email;
    private javax.swing.JTextField Endereco;
    private javax.swing.JTextField Nome;
    private javax.swing.JTextField Sobrenome;
    private javax.swing.JTextField Telefone;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField numero;
    // End of variables declaration//GEN-END:variables
}
